.dockerignore
.env
Dockerfile
docker-compose.local.yml
package.json

도커 설정했는데 잘 모르겠네요. 셤끝나고 물어보겠습니다.

build: docker

---

.vscode/settings.json
package-lock.json
package.json
src/app.module.ts
src/configuration/database.config.ts
src/feat/database/database.module.ts
src/feat/database/database.service.ts
src/feat/users/entities/user.entity.ts
tsconfig.json

mikro orm config설정 했습니다. env랑 db url 설정 해줘야합니다.
- [참고한 github](https://github.dev/mwanago/nestjs-mikroorm)

build: install and add mikro ORM

---

package-lock.json
package.json
src/app.module.ts

build: install and add joi

---

docker-compose.local.yml
package.json
src/app.module.ts
src/feature/api/users/presentation/users.controller.ts
src/main.ts

.env.develop 파일 변경되었습니다. [노션참고](https://www.notion.so/env-421d796562ba4f19a6c6962f5a8764b3?pvs=4)

Fix: api 변경 적용, local port 8080

---

src/feature/api/users/presentation/users.controller.ts

프로필 이미지 파일 이름을 profile 에서 profileImage로 바꿨습니당

chore : POST profie-image 인자 이름 변경

---

src/feature/api/channels/application/channel.service.ts
src/feature/api/channels/infrastructure/channel-message.entity.ts
src/feature/api/channels/infrastructure/channel-participant.entity.ts
src/feature/api/channels/infrastructure/channel-user-banned.entity.ts
src/feature/api/channels/infrastructure/channel.entity.ts
src/feature/api/channels/presentation/gateway/channel.gateway.ts
src/feature/api/users/infrastructure/banned-user.entity.ts
src/feature/api/users/infrastructure/dm-message.entity.ts
src/feature/api/users/infrastructure/dm.entity.ts
src/feature/api/users/infrastructure/friend-request.entity.ts
src/feature/api/users/infrastructure/friend.entity.ts
src/feature/api/users/infrastructure/user.entity.ts
src/migrations/.snapshot-postgres.json
src/migrations/Migration20231125072050.ts
src/migrations/Migration20231125081428.ts

<br/>
Entity 클래스의 One to many관계의 타입을 string으로 바꿔주었어요: 이제 id만 접근 가능합니다!
<br/>
객체 전체가 매핑되지 않도록 :>
<br/>
- 제대로 잘 돌아가기 위해 일부 코드를 주석처리했어요: channel.service.ts
<br/>
<br/>

Refactor: change db entity

---

src/feature/api/users/presentation/controller/friends.controller.ts
src/feature/api/users/presentation/controller/users.controller.ts
src/feature/api/users/users.module.ts

<br/>
user controller에 friends부분을 분리했습니다.
<br/>
- user컨트롤라가 너무 커서 분리가 필요해 보였습니다.
<br/>
<br/>
기능에는 영향이 없을것 같아서 바로 머지 하겠습니다.
<br/>

Chore(users): move to friends controller

---

package-lock.json
package.json
src/feature/api/users/infrastructure/user.entity.ts
src/seeders/DatabaseSeeder.ts
src/seeders/friend-request.factory.ts
src/seeders/friend.factory.ts
src/seeders/user.factory.ts

<br/>
Seeder 구현했습니다. 간단하게 3개만 예제로 구현했습니다. 아래와같이 필요한부분 구현하면 될것같습니다.
더미데이터 리턴하는부분 db에서 return할수 있을것같아요.
추가적으로 db reset도 필요하려나하는 생각이 있습니다.
<br/>
<br/>
<br/>
<br/>

[Build] seeder 구현

---

src/app.module.ts
src/feature/api/api.module.ts
src/feature/api/channels/application/channel.service.ts
src/feature/api/channels/domain/channel-message.ts
src/feature/api/channels/domain/channel-participant.ts
src/feature/api/channels/domain/channel-user-banned.ts
src/feature/api/channels/domain/channel.repository.ts
src/feature/api/channels/domain/channel.ts
src/feature/api/channels/infrastructure/channel-message.entity.ts
src/feature/api/channels/infrastructure/channel-participant.entity.ts
src/feature/api/channels/infrastructure/channel-user-banned.entity.ts
src/feature/api/channels/infrastructure/channel.entity.ts
src/feature/api/channels/presentation/gateway/channel.gateway.ts
src/feature/api/users/domain/banned-user.ts
src/feature/api/users/domain/dm/dm-message.ts
src/feature/api/users/domain/dm/dm.ts
src/feature/api/users/domain/friend/friend-request.ts
src/feature/api/users/domain/user.ts
src/feature/api/users/infrastructure/banned-user.entity.ts
src/feature/api/users/infrastructure/dm-message.entity.ts
src/feature/api/users/infrastructure/dm.entity.ts
src/feature/api/users/presentation/controller/users.controller.ts
src/main.ts
src/migrations/Migration20231126112103.ts
src/migrations/Migration20231126131819.ts
src/migrations/Migration20231201080714.ts
src/seeders/DatabaseSeeder.ts
src/seeders/friend-request.factory.ts
src/seeders/friend.factory.ts
src/seeders/user.factory.ts

<br/>
무엇을 합니다!
- 이 일을 했다!
- 이 일도 했다!
<br/>
<br/>
<br/>
<br/>

[chore]: prettier

---

src/feature/api/users/presentation/controller/friends.controller.ts

<br/>
params에서 decorator로 변경되야하는거 추가했습니다.
<br/>
<br/>
<br/>
<br/>

[Chore] add annotation and user id for test

---

src/feature/api/channels/infrastructure/channel-participant.entity.ts
src/feature/api/channels/infrastructure/channel-user-banned.entity.ts
src/feature/api/channels/infrastructure/channel.entity.ts
src/feature/api/channels/presentation/gateway/channel.gateway.ts
src/feature/api/users/domain/user.ts
src/feature/api/users/infrastructure/user.entity.ts
src/feature/api/users/infrastructure/user.repository.impl.ts
src/migrations/.snapshot-postgres.json
src/migrations/Migration20231205131234.ts

<br/>
무엇을 합니다!
- channel, channelParticipant, channelUserBanned 에 isDeleted 추가했습니다
- user에도 isDeleted 추가하면서 user.ts user.repository.impl.ts 파일도 변경사항 있었습니다
- migration 적용 완료후 json, migration 파일도 같이 업로드 했습니다
<br/>
- 소프트딜리트 관련한 이유로 추가했습니다
<br/>
<br/>
user 관련해서 user.ts 랑 toDomain, toEntity 추가된게 있는데 문제없는지 확인부탁드려요~ @besyia0k0 
<br/>

Build/entity isDeleted 추가 관련 엔티티 변동사항 있었습니다

---

src/feature/api/users/domain/user.ts
src/feature/api/users/infrastructure/user.entity.ts
src/feature/api/users/infrastructure/user.repository.impl.ts
src/migrations/.snapshot-postgres.json
src/migrations/Migration20231209064144.ts

<br/>
이메일 인증을 위해 두 가지 컬럼을 추가했습니다.
- isValidatieEmail: 검증된 이메일인지 확인용
- verificationCode: 인증 코드 암호화하여 저장할 column
<br/>
이메일 인증에 필요해서 추가했습니다!
<br/>
- 정상 실행 확인했습니다 ~!
<br/>
<br/>

[Feature] Add user entity column to email verification

---

src/feature/api/users/application/friends/delete-friend.use-case.ts
src/feature/api/users/application/friends/find-acceptable-friend-request.use-case.ts
src/feature/api/users/application/friends/friend-request.use-case.ts
src/feature/api/users/domain/friend/friend-request.ts
src/feature/api/users/domain/friend/interface/friend-request.repository.ts
src/feature/api/users/domain/friend/interface/friend.repository.ts
src/feature/api/users/infrastructure/repositories/friend-request.repository.impl.ts
src/feature/api/users/infrastructure/repositories/friend.repository.impl.ts
src/feature/api/users/presentation/controller/friends.controller.ts
src/feature/api/users/presentation/view-models/friends-request/find-friends-request.vm.ts
src/feature/api/users/users.module.ts

<br/>
무엇을 합니다!
- delete friend 구현
- find friends request 구현
<br/>
<br/>
<br/>
<br/>

[Feature]:  delete friends 구현 && get friends request 구현

---

src/feature/api/channels/application/channel.service.ts
src/feature/api/channels/domain/channel-participant.ts
src/feature/api/channels/domain/channel-user-banned.ts
src/feature/api/channels/domain/channel.ts
src/feature/api/channels/domain/repositories/channel-message.repository.ts
src/feature/api/channels/domain/repositories/channel-participant.repository.ts
src/feature/api/channels/domain/repositories/channel-user-banned.repository.ts
src/feature/api/channels/domain/repositories/channel.repository.ts
src/feature/api/channels/infrastructure/channel.entity.ts
src/feature/api/channels/presentation/gateway/channel.gateway.ts

<br/>
무엇을 합니다!
- 킥, 밴, 뮤트, 방장이 나갔을때, 관리자 권한등 구현해보았습니다!
<br/>
<br/>
- 대강 테스트 해보았으나 유저 여러명일때 테스트가 안되어서 jwt 되고나서 수정하사항이 생길수도 있을것 같아요
<br/>
<br/>

Feature/channel channel 거의 끝났습니다!

---

src/feature/api/users/application/use-case/users.use-case.ts
src/feature/api/users/domain/user.repository.ts
src/feature/api/users/infrastructure/user.repository.impl.ts
src/feature/api/users/presentation/controller/users.controller.ts
src/feature/api/users/presentation/view-models/users/find-users.vm.ts

<br/>
무엇을 합니다!
- users 에 get all 뷰모델 만들어서 구현했습니다
<br/>
- jwt 소통을 위한 빅픽쳐
<br/>
- 두개의 유저 만들었을때 잘 받아와지는지 확인했어요
<br/>
그렇지만 all users했을때 사용자 본인도 같이 받아와져서 이거 처리해줘야할뜻
<br/>

Feature/user get all 살짝 추가해보았습니다

---

src/feature/api/auth/application/use-case/two-factor-auth.use-case.ts
src/feature/api/auth/presentation/controller/two-factor-auth.controller.ts

<br/>
2fa 요청 시 이메일 주소를 보내도록 수정했습니다!
<br/>
- 프론트 요청으로 인해 변경했습니다
<br/>
- 정상작동하는 것 확인했습니다~
<br/>
<br/>

[Feature] 2fa 시 이메일 주소 리턴

---

src/feature/api/notification/application/dm.use-case.ts
src/feature/api/notification/domain/repositories/dm.repository.ts
src/feature/api/notification/notification.module.ts
src/feature/api/notification/presentation/notification.gateway.ts
src/feature/api/users/application/friends/friend-request.use-case.ts
src/feature/api/users/users.module.ts

<br/>
dm방 수락 로직 작성했습니다.
- 친구가 되었을 때 dm방도 함께 생성됩니다.
- 이 과정에서 UserModule과 NotificationModule이 Circular Dependency가 되어서 공식 문서대로 고치긴 했는데 왠지 찝찝합니다 .....
<br/>
- 친구 수락 시 dm 생성되어야 함!
<br/>
- 프론트 이용하여 방 생성되는 것 확인
- block이 머지되지 않아 블럭 풀고 잘 되는지는 앞선 풀리퀘 머지 후 확인해보도록 하겠습니다~
<br/>
<br/>

[Feature] 친구 수락 시 dm방 생성

---

src/feature/api/users/presentation/controller/friends.controller.ts

<br/>
isFriend api에서 name을 기반으로 찾을 수 있도록 변경하였습니다.
<br/>
- api 설계 변경!
<br/>
- 정상 작동 확인했습니다 ~
<br/>
<br/>

[Fix] change isFriend api by friend name

---

src/feature/api/channels/presentation/gateway/dto/create-channel.dto.ts
src/feature/api/users/presentation/dto/update-user.dto.ts

<br/>
user name은 비어있거나 스페이스 바가 들어가면 안됩니다!
따라서 class validator 이용해서 막아주었습니다~
<br/>
- 테스트 중 발견 ~~
<br/>
- postman 이용해서 정상 작동 확인했습니다~
<br/>
<br/>

[Fix] name should not empty or have space character

---

src/feature/api/users/presentation/controller/users.controller.ts

<br/>
메인 페이지 인터페이스 맞춰서 더미데이터 작성했습니다!
<br/>
- users에 있던것들 엔티티에 맞게 몇개 바꿨어염
<br/>
<br/>
<br/>

Feature/main main page Dummy Data interface

---

src/feature/api/auth/tools/socketTools.ts

<br/>
자꾸 JWT malform에러가 나서 보니까 null이 문자열로 들어오는 이슈가 있더라고요
그래서 'null'을 잡아주니까 해결 됐습니다!
<br/>
- 자꾸 에러나서
<br/>
<br/>
<br/>

Fix: Socket Malform Error

---

src/feature/api/channels/infrastructure/channel-message.entity.ts
src/feature/api/channels/infrastructure/channel-participant.entity.ts
src/feature/api/channels/infrastructure/channel-user-banned.entity.ts
src/feature/api/channels/infrastructure/channel.entity.ts
src/feature/api/game/application/game-with-player.use-case.ts
src/feature/api/game/application/game.use-case.ts
src/feature/api/game/domain/game.ts
src/feature/api/game/domain/interface/game.repository.ts
src/feature/api/game/domain/interface/player-score.repository.ts
src/feature/api/game/domain/player-score.ts
src/feature/api/game/game.module.ts
src/feature/api/game/infrastructure/game.entity.ts
src/feature/api/game/infrastructure/player-score.entity.ts
src/feature/api/game/infrastructure/repository/game.repository.impl.ts
src/feature/api/game/infrastructure/repository/player-score.repository.impl.ts
src/feature/api/game/presentation/type/tier.enum.ts
src/feature/api/notification/infrastructure/dm-message.entity.ts
src/feature/api/notification/infrastructure/dm.entity.ts
src/feature/api/users/infrastructure/blocked-user.entity.ts
src/feature/api/users/infrastructure/friend-request.entity.ts
src/feature/api/users/infrastructure/friend.entity.ts
src/feature/api/users/infrastructure/user.entity.ts
src/feature/api/users/presentation/controller/users.controller.ts
src/feature/api/users/presentation/view-models/users/match.vm.ts
src/feature/api/users/users.module.ts

<br/>
게임 관련한 정보를 메인화면에서 볼 수 있게, 기존 더미 데이터를 실제 데이터로 변경하였습니다.
- user rank 및 user match history
<br/>
- 엄청난 메인화면 -!!
<br/>
- 프론트에서 작동 시 제대로 작동됨을 확인했습니다!
<br/>
**database 수정 있습니다** : Migration 필요!!
* game 관련한 entity에 createdAt, updatedAt 추가했습니다
* 게임 당시의 playerA, playerB를 순서 변경 없이 가져올 수 있도록!
<br/>

[Feature] game information 메인 페이지 api 작성 완료

---

src/feature/api/game/application/game.use-case.ts
src/feature/api/game/presentation/type/tier.enum.ts
src/feature/api/notification/presentation/type/ladder-match.ts
src/feature/api/users/application/use-case/users.use-case.ts
src/feature/api/users/infrastructure/user.repository.impl.ts

<br/>
무엇을 합니다!
- tier enum타입 변수를 다 소문자로 바꿨습니다
<br/>
- enum으로 변환할때 대소문자 때문에 변환이 안돼서 enum 변수이름을 대문자로 바꿨습니다
<br/>
<br/>
<br/>

[Fix] game-tier 컴팩트한 pr날리겠습니다 핫픽스~

---

src/feature/api/users/presentation/dto/create-user.dto.ts

<br/>
profile image의 default 값의 서버를 env에서 가져옵니다.
<br/>
- 기존에 string으로 존재하는 값을 변경했습니다.
<br/>
- insomnia로 테스트 완료했습니다.
<br/>
<br/>

[Fix] change server url

---

src/feature/api/game/presentation/game.gateway.ts
src/feature/api/notification/presentation/notification.gateway.ts

<br/>
게임 관련 오류 수정했습니다.
- 게임 거절 시 내 화면에서 사라지지 않는 오류
- pre-game에서 나갈 때 기권패, 업적 달성되지 않음
- 게임 오버 시 두 번 저장되는 오류
더불어, 매치 아이디는 두 유저의 소켓 아이디를 기반으로 결정됩니다.
<br/>
- 몇몇 이슈!
<br/>
- 프론트랑 같이 오류 보며 작업했습니다~
<br/>
<br/>

[Fix] game 수정사항

---

src/feature/api/auth/auth.module.ts
src/feature/api/game/presentation/game.gateway.ts
src/feature/api/notification/presentation/notification.gateway.ts
src/feature/api/notification/presentation/type/ladder-match-queue.ts
src/feature/api/users/application/friends/friend-request.use-case.ts
src/feature/api/users/application/use-case/users.use-case.ts
src/feature/api/users/domain/user.ts
src/feature/api/users/infrastructure/user.repository.impl.ts
src/feature/api/users/presentation/controller/friends.controller.ts
src/feature/api/users/presentation/controller/users.controller.ts
src/feature/api/users/presentation/dto/update-user.dto.ts
src/feature/api/users/users.module.ts
src/feature/api/users/users.service.ts

<br/>
user 관련 일부 로직을 변경합니다.
- 게임하게 될 시 user의 status를 in-game으로 변화시킵니다.
- user 2fa enable 시 유저 이메일이 존재하고, validation 되었다면 2fa validate를 true로 바꿉니다.
- name duplicated 할 시, 본인 닉네임을 해당 값으로 변경 후 본인을 제외한 사람들 내에서 duplicated를 찾습니다.
- 본인 정보 변경를 위한 myInfo api를 추가했습니다.
<br/>
- 오류 발견 !
<br/>
- 프론트와 테스트 완료, insomnia로도 확인했습니다.
<br/>
<br/>

[Feature] add user status in-game

---

src/feature/api/notification/notification.module.ts
src/feature/api/notification/presentation/notification.gateway.ts
src/feature/api/users/application/friends/create-friend-request.use-case.ts
src/feature/api/users/application/friends/friend-request.use-case.ts
src/feature/api/users/application/use-case/blocked-user.use-case.ts
src/feature/api/users/infrastructure/user.repository.impl.ts
src/feature/api/users/presentation/controller/friends.controller.ts

<br/>
무엇을 합니다!
친구 요청이랑 current status 바뀌는거 소켓구현 했습니다!
<br/>
<br/>
<br/>
<br/>

[Feature] emit in social, alarm

---

src/feature/api/notification/presentation/notification.gateway.ts

<br/>
소켓에서 중복 로그인 여부를 확인하는 코드를 짰습니다.
아좌잣
<br/>
<br/>
<br/>
<br/>

Feat: Prevent Double Login

---

src/feature/api/notification/presentation/notification.gateway.ts
src/feature/api/users/infrastructure/user.repository.impl.ts

<br/>
테스트 중 생긴 버그들을 고칩니다.
- 이름이 존재하지 않는 유저는 getAll에서 받아지지 않습니다.
- 이미 게임 요청이 존재하는 두 유저 간 새로운 요청을 생성하지 않습니다.
<br/>
- 버그 발생!
<br/>
- 프론트와 테스트 완료했습니다.
<br/>
<br/>

[Fix] 테스트 중 생긴 버그 fix(게임 요청, getAll)

---

src/feature/api/game/presentation/game.gateway.ts

<br/>
게임 시간이 변하지 않는 버그.... 고쳤습니다..
<br/>
- 코드 짜면서 하나에 대한 인터벌인줄 알고 게임이 끝나면 지웠더니 이런 사태가 벌어졌습니다 ..ㅠ 이제 지우지 않습니다!
<br/>
<br/>
<br/>

[Fix] do not stop update game time cron

---

src/feature/api/game/presentation/type/player.ts
src/feature/api/users/presentation/view-models/users/match.vm.ts

<br/>
- date string을 한국 시간에 맞춰 변경해줬습니다.
- speed가 변함에 따라 ball spin 시 변화값도 수정해줬습니다. 
<br/>
- 완벽한 트센을 위해 ...~
<br/>
<br/>
<br/>

[Fix] change date string to kor time, spin change

---

src/feature/api/notification/presentation/notification.gateway.ts

<br/>
무엇을 합니다!
- 소셜에서 더블탭 했을때 꺼지는 에러가 있었죠? 하지만 제가 해결 해 드렸습니다~ ㅋ
<br/>
<br/>
<br/>
<br/>

[fix] big error but small solution in double tap

---

src/feature/api/channels/presentation/gateway/channel.gateway.ts
src/feature/api/game/presentation/game.gateway.ts
src/feature/api/game/presentation/type/player.ts
src/feature/api/notification/presentation/notification.gateway.ts
src/feature/api/users/presentation/view-models/users/match.vm.ts

<br/>
- game reset ball을 공을 움직인 상황에서 즉시 진행합니다.
- dm/channel message size가 db 설정 사이즈보다 크면 오류를 보냅니다.
<br/>
- 버그진짜그만 ...
<br/>
<br/>
<br/>

[Fix] test debugging

---

src/feature/api/game/presentation/game.gateway.ts

<br/>
무엇을 합니다!
- 게임소켓에 스테이터스 업데이트 안되는거 에밋했지
<br/>
<br/>
<br/>
<br/>

[fix] emit changeStatus in game socket

---

entry.sh
src/feature/api/channels/application/channel.service.ts
src/feature/api/channels/presentation/gateway/channel.gateway.ts
src/feature/api/users/application/friends/friend-request.use-case.ts
src/feature/api/users/application/friends/friend.use-case.ts
src/feature/api/users/application/use-case/blocked-user.use-case.ts
src/feature/api/users/application/use-case/users.use-case.ts

<br/>
테스트 중 발견한 버그를 픽스합니다.
- async-await 부재로 인한 transaction error
- friend request -> block -> request accept 시 block & 친구 되는 버그
<br/>
- 엄청난 테스트
<br/>
- 부탁드립니다 (_ _)
<br/>
<br/>

[Fix] async-await 적용, block 시 friend request reject

---

src/feature/api/notification/domain/repositories/dm.repository.ts
src/feature/api/notification/presentation/notification.gateway.ts
src/feature/api/users/infrastructure/repositories/achievement-status.repository.impl.ts
src/feature/api/users/infrastructure/repositories/blocked-user.repository.impl.ts

<br/>
논리적으로 같은 데이터가 존재하지 않아야 할 경우, create를 하지 않도록 합니다.
최대한 오류가 발생하지 않도록 수정했습니다.
<br/>
- 오류방지
<br/>
<br/>
<br/>

[Fix] improve validation

---

src/feature/api/notification/application/dm.use-case.ts
src/feature/api/notification/presentation/notification.gateway.ts
src/feature/api/users/infrastructure/repositories/friend-request.repository.impl.ts
src/feature/api/users/infrastructure/repositories/friend.repository.impl.ts

<br/>
무엇을 합니다!
- await 빠진거 붙여줬어용
<br/>
<br/>
<br/>
<br/>

[fix] async await 빠진거 최종으로 풀리퀘날립니다!
